const mongoose = require("mongoose");
const Schema = mongoose.Schema({
  user: { type: String },
  projectName: { type: String },
  Risk_Compliance: { type: String },
  Risk_Standards1: { type: String },
  Risk_Standards2: { type: String },
  Risk_DataGov1: { type: String },
  Risk_DataGov2: { type: String },
  Risk_DataGov3: { type: String },
  Risk_DataGov4: { type: String },
  Risk_InfoSec1: { type: String },
  Risk_InfoSec2: { type: String },
  Risk_InfoSec3: { type: String },
  Risk_BusCon1: { type: String },
  Risk_BusCon2: { type: String },
  Tech_Virtualization1: { type: String },
  Tech_Virtualization2: { type: String },
  Tech_Legacy1: { type: String },
  Tech_Legacy2: { type: String },
  Tech_AppDepend1: { type: String },
  Tech_AppDepend2: { type: String },
  Tech_users: { type: String },
  Tech_LifecycMan1: { type: String },
  Tech_LifecycMan2: { type: String },
  Tech_Licensing1: { type: String },
  Tech_Licensing2: { type: String },
  Tech_Network1: { type: String },
  Tech_Network2: { type: String },
  Tech_Network3: { type: String },
  Tech_Network4: { type: String },
  Tech_Workload1: { type: String },
  Tech_Workload2: { type: String },
  Tech_Architecture1: { type: String },
  Tech_Architecture2: { type: String },
  Tech_Architecture3: { type: String },
});

const UserModel = mongoose.model("projects", Schema);
module.exports = UserModel;
